# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Android',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('Android_version', models.CharField(blank=True, max_length=50)),
                ('Physical_size', models.CharField(blank=True, max_length=50)),
                ('owner', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField()),
                ('createdtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(default='Android', max_length=50)),
                ('applicant', models.CharField(blank=True, max_length=50)),
                ('breakdown', models.BooleanField(default=True)),
                ('assetnum', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='borrowHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicename', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('managername', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('createdtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('assetnum', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='iOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('iOS_version', models.CharField(blank=True, max_length=50)),
                ('Physical_size', models.CharField(blank=True, max_length=50)),
                ('owner', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField()),
                ('createdtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(default='iOS', max_length=50)),
                ('applicant', models.CharField(blank=True, max_length=50)),
                ('breakdown', models.BooleanField(default=True)),
                ('assetnum', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
