# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-26 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='android',
            old_name='createtime',
            new_name='createdtime',
        ),
        migrations.RenameField(
            model_name='ios',
            old_name='createtime',
            new_name='createdtime',
        ),
        migrations.AddField(
            model_name='android',
            name='modifiedtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ios',
            name='modifiedtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='android',
            name='Android_version',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='android',
            name='Physical_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='android',
            name='owner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ios',
            name='Physical_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ios',
            name='iOS_version',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ios',
            name='owner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
