# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0002_auto_20170526_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='android',
            name='brand',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ios',
            name='brand',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
