# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0003_auto_20170601_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ios',
            name='brand',
        ),
    ]
