# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-02 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0004_remove_ios_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='android',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ios',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
