# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0005_auto_20170602_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrowHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicename', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=10)),
                ('managername', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
