# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-05 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0006_borrowhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=10)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('modifiedtime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='android',
            name='system',
            field=models.CharField(default='Android', max_length=10),
        ),
        migrations.AddField(
            model_name='ios',
            name='system',
            field=models.CharField(default='iOS', max_length=10),
        ),
        migrations.AddField(
            model_name='apply',
            name='Android_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phone.Android'),
        ),
        migrations.AddField(
            model_name='apply',
            name='iOS_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phone.iOS'),
        ),
    ]
