# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-05 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0008_auto_20170605_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apply',
            new_name='applyList',
        ),
    ]
