# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-05 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0009_auto_20170605_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applylist',
            old_name='Android_id',
            new_name='Android',
        ),
        migrations.RenameField(
            model_name='applylist',
            old_name='iOS_id',
            new_name='iOS',
        ),
    ]
