# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-05 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0010_auto_20170605_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='android',
            name='applicant',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ios',
            name='applicant',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
