# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-06 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0011_auto_20170605_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='android',
            name='breakdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ios',
            name='breakdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='android',
            name='applicant',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ios',
            name='applicant',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
