# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0012_auto_20170606_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='android',
            name='assetnum',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='assetnum',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ios',
            name='assetnum',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
