# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-09 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0013_auto_20170608_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='android',
            name='createdtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='createdtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ios',
            name='createdtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
