# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-12 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0014_auto_20170609_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='android',
            name='Android_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='android',
            name='Physical_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='android',
            name='applicant',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='android',
            name='assetnum',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='android',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='android',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='android',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='android',
            name='system',
            field=models.CharField(default='Android', max_length=50),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='applicant',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='status',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='assetnum',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='devicename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='managername',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='owner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ios',
            name='Physical_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ios',
            name='applicant',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ios',
            name='assetnum',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ios',
            name='iOS_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ios',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ios',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ios',
            name='system',
            field=models.CharField(default='iOS', max_length=50),
        ),
    ]
