# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-13 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0015_auto_20170612_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='ios',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='android',
            name='Android_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ios',
            name='iOS_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
